### ISSUE TITLE
Tele2

### ISSUE THREAD

**Issue by pistonov** [agentsib/useful-scripts#2]
Проверка баланса tele2 не работает. 
Можешь починить?

**Comment by agentsib** [comment]
Опять поменяли дизайн кабинета... Как время появиться - сделаю.

**Comment by pistonov** [comment]
Спасибо.

**Comment by agentsib** [comment]
Спасибо за МР. На основе него сделал коммит. Проверьте.

**Comment by pistonov** [comment]
Отлично, все работает. Спасибо за помощь.
